  import os
  import requests
  import telebot
  from telebot import types
  from flask import Flask, request

  # Токен бота из настроек Render
  BOT_TOKEN = os.environ.get('BOT_TOKEN')
  bot = telebot.TeleBot(BOT_TOKEN)

  app = Flask(__name__)

  # Хранилище в памяти для загруженных файлов (PDF и MP3)
  user_books = {}  # chat_id: list of file_ids/names
  user_music = {}  # chat_id: list of file_ids/names

  # Главное меню с кнопками 🔘
  def get_main_keyboard():
      keyboard = types.InlineKeyboardMarkup()

              btn_books = types.InlineKeyboardButton(text="📚 Мои Книги (PDF)", callback_data="books")
                  btn_facts = types.InlineKeyboardButton(text="💡 Случайный факт", callback_data="facts")
                      btn_weather = types.InlineKeyboardButton(text="🌦️ Погода", callback_data="weather")
                          btn_music = types.InlineKeyboardButton(text="🎵 Моя Музыка (MP3)", callback_data="music")

                                  keyboard.add(btn_books, btn_facts)
                                      keyboard.add(btn_weather, btn_music)

                                              return keyboard

                                              # Команда /start
                                              @bot.message_handler(commands=['start'])
                                              def start_message(message):
                                                  bot.send_message(
                                                          message.chat.id, 
                                                                  "Привет! Я твой многофункциональный бот. 🤖\n\n"
                                                                          "• Нажимай кнопки меню ниже\n"
                                                                                  "• Отправляй мне **PDF-файлы** (книги)\n"
                                                                                          "• Отправляй мне **MP3-файлы** (музыку)\n"
                                                                                                  "• Напиши название любого города, чтобы узнать погоду!", 
                                                                                                          reply_markup=get_main_keyboard(),
                                                                                                                  parse_mode="Markdown"
                                                                                                                      )

                                                                                                                      # Обработка нажатий на кнопки 🖱️
                                                                                                                      @bot.callback_query_handler(func=lambda call: True)
                                                                                                                      def handle_menu_click(call):
                                                                                                                          bot.answer_callback_query(call.id)
                                                                                                                              chat_id = call.message.chat.id

                                                                                                                                      if call.data == "facts":
                                                                                                                                              # Бесплатный API интересных фактов 💡
                                                                                                                                                      try:
                                                                                                                                                                  res = requests.get("https://uselessfacts.jsph.pl/api/v2/facts/random")
                                                                                                                                                                              if res.status_code == 200:
                                                                                                                                                                                              fact_text = res.json().get('text')
                                                                                                                                                                                                              bot.send_message(chat_id, f"💡 **Интересный факт:**\n{fact_text}", parse_mode="Markdown")
                                                                                                                                                                                                                          else:
                                                                                                                                                                                                                                          bot.send_message(chat_id, "Не удалось получить факт, попробуй ещё раз!")
                                                                                                                                                                                                                                                  except Exception:
                                                                                                                                                                                                                                                              bot.send_message(chat_id, "Ошибка при запросе к API фактов.")

                                                                                                                                                                                                                                                                              elif call.data == "weather":
                                                                                                                                                                                                                                                                                      bot.send_message(chat_id, "🌦️ Просто напиши мне название города в чат (например: *Москва*, *Ташкент*, *Лондон*), и я покажу погоду!", parse_mode="Markdown")

                                                                                                                                                                                                                                                                                                  elif call.data == "books":
                                                                                                                                                                                                                                                                                                          books = user_books.get(chat_id, [])
                                                                                                                                                                                                                                                                                                                  if not books:
                                                                                                                                                                                                                                                                                                                              bot.send_message(chat_id, "📚 У тебя пока нет сохранённых PDF-книг.\nПросто отправь мне любой **PDF-файл**, и я его сохраню!", parse_mode="Markdown")
                                                                                                                                                                                                                                                                                                                                      else:
                                                                                                                                                                                                                                                                                                                                                  bot.send_message(chat_id, f"📚 Твои сохранённые книги ({len(books)}):")
                                                                                                                                                                                                                                                                                                                                                              for book in books:
                                                                                                                                                                                                                                                                                                                                                                              bot.send_document(chat_id, book['file_id'], caption=f"📖 {book['name']}")

                                                                                                                                                                                                                                                                                                                                                                                                  elif call.data == "music":
                                                                                                                                                                                                                                                                                                                                                                                                          tracks = user_music.get(chat_id, [])
                                                                                                                                                                                                                                                                                                                                                                                                                  if not tracks:
                                                                                                                                                                                                                                                                                                                                                                                                                              bot.send_message(chat_id, "🎵 У тебя пока нет сохранённых MP3-треков.\nПросто отправь мне любой **MP3-файл**, и я его сохраню!", parse_mode="Markdown")
                                                                                                                                                                                                                                                                                                                                                                                                                                      else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                  bot.send_message(chat_id, f"🎵 Твоя библиотека музыки ({len(tracks)}):")
                                                                                                                                                                                                                                                                                                                                                                                                                                                              for track in tracks:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              bot.send_audio(chat_id, track['file_id'], caption=f"🎧 {track['name']}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Прием и сохранение PDF документов 📚
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              @bot.message_handler(content_types=['document'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              def handle_document(message):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if message.document.mime_type == 'application/pdf':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          chat_id = message.chat.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  file_id = message.document.file_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          file_name = message.document.file_name or "Книга.pdf"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if chat_id not in user_books:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user_books[chat_id] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              user_books[chat_id].append({'file_id': file_id, 'name': file_name})

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              bot.reply_to(message, f"📚 Книга **«{file_name}»** сохранена! Нажми кнопку «Мои Книги» в меню, чтобы просмотреть.", parse_mode="Markdown")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          bot.reply_to(message, "Пожалуйста, отправь файл в формате PDF.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # Прием и сохранение MP3 музыки 🎵
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @bot.message_handler(content_types=['audio'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          def handle_audio(message):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              chat_id = message.chat.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  file_id = message.audio.file_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      track_name = message.audio.title or message.audio.file_name or "Аудиозапись"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if chat_id not in user_music:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user_music[chat_id] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          user_music[chat_id].append({'file_id': file_id, 'name': track_name})

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bot.reply_to(message, f"🎵 Трек **«{track_name}»** сохранён! Нажми кнопку «Моя Музыка» в меню, чтобы послушать.", parse_mode="Markdown")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # Бесплатный поиск погоды по названию города 🌦️
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  @bot.message_handler(func=lambda message: True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  def handle_text(message):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      city = message.text.strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # Используем бесплатный публичный API wttr.in
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res = requests.get(f"https://wttr.in/{city}?format=3")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if res.status_code == 200 and "Unknown location" not in res.text:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              bot.reply_to(message, f"🌦️ **Погода:**\n{res.text}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bot.reply_to(message, f"Не удалось найти город «{city}». Попробуй написать название на английском или проверь ошибки.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              bot.reply_to(message, "Ошибка при запросе погоды.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Маршруты Webhook 🌐
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              @app.route('/' + BOT_TOKEN, methods=['POST'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              def getMessage():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  json_string = request.get_data().decode('utf-8')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      update = telebot.types.Update.de_json(json_string)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          bot.process_new_updates([update])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return "!", 200

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              @app.route("/")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              def webhook():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bot.remove_webhook()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      bot.set_webhook(url='https://my-book-bot-9ga9.onrender.com/' + BOT_TOKEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return "Bot is running!", 200

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              app.run(host="0.0.0.0", port=int(os.environ.get('PORT', 5000)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
